### ISSUE TITLE
Conda-forge release

### ISSUE THREAD

**Issue by ericmjl** [modernatx/seqlike#4]
We'll need to get automation up to release to conda-forge from PyPI. 

Depends on #3.

**Comment by sugatoray** [comment]
@ericmjl I had not seen `seqlike` on conda-forge and so independently had started the work of adding it to conda-forge. Just realized you have assigned this to yourself. 

https://github.com/conda-forge/staged-recipes/pull/17283

If you would prefer, I could add you as another maintainer for the feedstock.

**Comment by ericmjl** [comment]
Please do so, @sugatoray! Thank you very much!

**Comment by sugatoray** [comment]
@ericmjl I would need a little help with the license issue (https://github.com/Edinburgh-Genome-Foundry/codon-usage-tables/issues/7) of `python-codon-tables`. Please see the details in the issue. 

I am not sure what text should be included for a *Public Domain* license? A license is necessary for conda-forge packaging.

Please advise.

**Comment by sugatoray** [comment]
## Thinking outside the box

In my **non-legal understanding** of the situation, a possible option here could be: if you happen to fork the said repository and then publish a pypi package (and keep updating the forked-repo as an exact replica of the original upstream repo), then you could decide to package it with a license of your choice (please seek advise from any legal team). Then, if `seqlike` uses this new pypi package, license limitation will not be an issue (hopefully).

**Comment by sugatoray** [comment]
## A side note

It appears that `seqlike` is now available on `bioconda` channel.

**Comment by ericmjl** [comment]
@sugatoray thank you for handling this issue! I have a hunch that Creative Commons' `CC0` license is what is needed, but as I can see on [this reply](https://github.com/Edinburgh-Genome-Foundry/codon-usage-tables/issues/7#issuecomment-996450437), you're already engaged with the `codon-usage-tables` maintainers to sanity-check.

Do you happen to know who released SeqLike to bioconda?

**Comment by sugatoray** [comment]
@ericmjl: I also had looked up all three recipes that are on bioconda now, and need to be transferred on to conda-forge. They are documented in the PR for conda-forge. I had shared a comment from the same PR here. You can see the others there as well.

**Comment by sugatoray** [comment]
`seqlike` is now available on conda-forge! 🚀✨🎉

I will send a PR to update the docs. 

cc: @ericmjl

## Major Activities Performed for this conda-forge update

1. **[DONE]** Create PR for `seqlike` recipe and update this repo via an issue. 
2. **[DONE]** Add dependencies (`weblogo` and `python-codon-tables`) as separate recipes in the same PR. 
3. **[DONE]** Open issues with dependencies that had license issues. 
4. **[DONE]** Manually scan entire repository of `weblogo` to extract various licenses for vendored software (such as code taken from biopython and used in weblogo). Conda-forge packaging needs all such licenses, not just the repository license. 
5. **[DONE]** All three of these libraries were under bioconda channel. So, to port them to conda-forge, permission was necessary from bioconda core team. Once, I received the permission, that hurdle was over. 
6. **[DONE]** License related issues, once solved, and when all packages were created successfully on the CI's, finally, almost after 3 weeks, the PR was merged. 
7. **[DONE]** The dependencies ran first and showed up on conda-forge. But `seqlike` needed a manual rerender, to get it on conda-forge. 
8. **[DONE]** Separate PRs were opened to update all three feedstocks with bioconda porting related information (to avoid future confusion). Maintainers from corresponding bioconda recipes were added to respective conda-forge feedstocks. 
9. **[DONE]** An issue was opened at bioconda repo to track removal of the recipes from bioconda, since bioconda channel inherits from conda-forge. And it is a best practice to avoid recipe duplication whenever possible. 
10. **[TODO]** Add @ericmjl as a maintainer.
