### ISSUE TITLE
[BUG] `seq_type` handling during instantiation

### ISSUE THREAD

**Issue by pagpires** [modernatx/seqlike#41]
I was playing around with the library (it was really nice and great job!) and hit this bug: 
instantiation like `SeqLike('ATCGATC')` or `SeqLike('ATCGATC', None)` will fail.  From the doc: 1) `seq_like` is supposedly optional but is required in the implementation ([code](https://github.com/modernatx/seqlike/blob/main/seqlike/SeqLike.py#L124)) and 2) logic regarding `seq_like==None` only occurs when `sequence` is a `SeqLike` ([code](https://github.com/modernatx/seqlike/blob/7ce029929434898c5ee0c688b5d15c6362b12e06/seqlike/SeqLike.py#L873)) as opposed to a native type and thus seems not very useful? (There's a `def determine__type()` ([code](https://github.com/modernatx/seqlike/blob/7ce029929434898c5ee0c688b5d15c6362b12e06/seqlike/SeqLike.py#L1096)) that I think is intended for the job but it's not used.) 

In addition, some general comments regarding dispatch, feel free to ignore them if they are out of context: 
`def _construct_seqlike` share the same signature for `alphabet` and `codon_map`, and `def determine__type_and_alphabet` share same signature for `seq_type` and `sequence`.  Thus it seems clearer to extract the only signature that varies? E.g. for the latter case we only dispatch functions based on `alphabet` (or even directly use `if alphabet==None: alphabet=determine_alphabet(_type, sequence)` rather than dispatching).  Current setup for these two functions seems to create duplicate logics and is error prone (types for `sequence` [here](https://github.com/modernatx/seqlike/blob/7ce029929434898c5ee0c688b5d15c6362b12e06/seqlike/SeqLike.py#L1072-L1084) should be the same?)

Again, happy to file a PR for anything specific above.

**Comment by pagpires** [comment]
Also a quick note: when dispatching for SeqLike, I guess we can use `SeqLikeType.__args__` as the type instead of hardcoding a list of potential types, otherwise it's hard to keep them consistent (since I saw there's a plan to include torch.tensor)

**Comment by ericmjl** [comment]
@pagpires thank you for chiming in! Yes, it looks like we have something wrong in the docs - by design, `SeqLike()` requires a sequence of letters and a `seq_type` to be specified. (I'm looking at the API reference [here](https://modernatx.github.io/seqlike/reference/seqlike/#seqlike.SeqLike.SeqLike.__init__).) However, it appears that the examples provided [here](https://modernatx.github.io/seqlike/reference/seqlike/#seqlike.SeqLike.SeqLike) don't show this. 

In a recent release, we decided to make 'factory functions', `aaSeqLike()` and `ntSeqLike()`, which return proper SeqLike objects but don't require specification of `seq_type` as an argument. Perhaps we could use some help making those two factory functions a bit more prominent. What are your thoughts on how this could be done better?

**Comment by ericmjl** [comment]
> Also a quick note: when dispatching for SeqLike, I guess we can use SeqLikeType.__args__ as the type instead of hardcoding a list of potential types, otherwise it's hard to keep them consistent (since I saw there's a plan to include torch.tensor)

I think this is a great idea. I'm going to make a new issue for this one as it feels like a unit of work that can be made as a PR.

**Comment by pagpires** [comment]
>In a recent release, we decided to make 'factory functions', aaSeqLike() and ntSeqLike()

That makes sense.  Then I think it's just that `SeqLike`'s docstring needs update.  It might also help to explicitly mention this api design in the development page in the doc, like "`nt/aaSeqlike` (user interface for instantiation) - `SeqLike` (data representation) - `_construct_seqlike` (logic under the hood)".  Just speaking for myself though.

**Comment by ericmjl** [comment]
Happy to handle this one. It's a small enough change and I know where to make the changes. :smile:.
