### ISSUE TITLE
Objects to represent mutations

### ISSUE THREAD

**Issue by ericmjl** [modernatx/seqlike#57]
I've encountered the situation where we need to represent mutations of a sequence. Having written essentially the same code over and over, I thought it might be good to talk about some of these ideas here.

I was thinking of something along the lines of two classes: a `Mutation` and a `MutationSet`. Defining them as classes allows for certain semantics:

```python
s = SeqLike('MKAIL')
mut = Mutation('A', 2, 'C')
# mut's repr would look like A3C
mut2 = Mutation('K', 1, 'R')
```

We may consider 'addition' to be an application of mutations to a reference sequence:

```python
s2 = s + mut
# s2 <-- SeqLike('MKCIL')

s2 = s + mut2
# s2 <-- SeqLike('MRAIL')
```

Mutations can also be offset by position:

```python
mut3 = mut - 1
# mut3 <-- A1C, but would raise an error if wt sequence does not have A at index 1.
```

If we need to hold multiple mutations together, we might use a `MutationSet`:

```python
mutations = MutationSet([mut, mut2])
# mutations <-- [K1R, A2C] (automatically sorted by position, then by letter)
s2 = s + mutations
# s2 <-- SeqLike('MRCIL')
```

MutationSets could also be offset by position:

```python
mutations + 1  # would give us [K2R, A3C]
```

We could also consider subtraction of two SeqLikes to give us the 'diff' as a MutationSet:

```python
mutset = s2 - s1  # (left is canonically considered the 'wt')
# mutset <-- [R1K, C2A]
mutset = s1 - s2 
# mutset <-- [K1R, A2C]
```

I'm not sure what other semantics I might have missed here. Any thoughts?

**UPDATE:** I changed the position numbers above to reflect Python indexing rules, not canonical indexing. I am sure we could magically handle both, but IMO because SeqLike uses Python indexing rules, Mutations and MutationSets should also use Python indexing rules for positions.

**Comment by ndousis** [comment]
This mutation representation capability would be very useful, and the arithmetic operations are a thoughtful and intuitive innovation!

General thoughts:

1. Deletions and insertions could also be represented by Mutation, e.g., `K2_` for a deletion. Nomenclature for insertions is trickier, perhaps something like `_2K` (insert a K after position 2)?

On position numbers:

2. Canonical numbering (per UniProt or the PDB) makes more intuitive sense to the biologist/biochemist, and this convention also helps maintain consistency across datasets (just ask anyone who has tried mapping between Rosetta renumbering and canonical numbering of PDBs). SeqLike currently represents position numbers ("seqnums" in the SeqRecord `letter_annotations`) as strings to capture the canonical numbering with insertion codes, e.g., like position "100F" in an antibody CDR-H3.
3. Would it be confusing to represent Python indices with integers, and canonical sequence numbers with strings? Or alternatively, have a derivative Mutation class called IndexMutation or similar?  The Mutation class could have a method called `to_index()` which returns an IndexMutation or the position number as a Python index.
4. A Python indexing convention makes it easier to apply a mutation to a Series of SeqLike, e.g., a multiple sequence alignment. The ability to interconvert from canonical number to Python index would facilitate the following workflow: I want to make a known mutation in Sequence A (e.g., to eliminate a catalytic residue) to the aligned position in Sequence B. This requires mapping the mutation position in Sequence A to the alignment index, and then the alignment index to the position number in Sequence B.


The concept of offsetting is intriguing but has challenges:

5. Offsetting is highly limited if the offset must have a matching amino acid identity; letting the WT amino acid identity change enables trivial alanine scans
6. **Offsetting requires a target sequence context**, but mapping to a single sequence could be highly restrictive or result in unexpected behavior if the same Mutation is applied to multiple sequences
7. Related to items 2 and 3, offsetting would work robustly only if the position number is a true Python index.

**Comment by andrewgiessel** [comment]
Sorry for the delayed feedback!

I think this is a nice idea that clearly addresses a common protein engineering need.  Really interesting to think through and the classes would add a lot of value for different workflows.

note: throughout this, I'm using the convention of `Mutation(X, #, Y)`.  I'd also like to point out that while this convention is well established, "X" (the "from" specifier) is sort of a bookkeeping hold-over for humans, and doesn't add anything for a computer besides enabling validation.  Offsets and the alanine scanning use-case are both more natural if we don't require it.

## Implementation at the SeqLike vs. SequenceLike level

This is likely the highest level design comment I have.  Despite this use case coming from biology, defined diffs seem general enough to apply at the SequenceLike level.  If this is taken as given, then IMO the following design considerations follow:

1) We should support arbitrary-based indexing, as the 1-based index is a biological convention, but 0 is python convention, as discussed above.  Swapping back and forth as above is really clunky.

2) We can't in a general sense rely on convention like "-" to mean gaps (or something like "*" as a wildcard), as SequenceLikes can have alphabets of any hashable object.  Related, there is no explicit notion of "aligned" SequenceLikes, and alignment potentially changes deletion semantics.

Taken together, these suggest that we might want 3 sub-classes of Mutation to represent Substitution, Insertion and Deletion.  SeqLike and SequenceLike would implement different `__add__` methods to reflect their most natural semantics.  

## MutationSet sorting
In the example above, @ericmjl suggested that we auto sort the mutations by position, then by letter (assuming he means "X").  This is reasonable, but I think needs to be explored more.  How well would this work with insertions or deletions?  Would it disallow some combinations of mutations by forcing an incompatible order?

## Insertion/Deletion Semantics
As noted by @ndousis, semantics around deletion and insertions will require some thought.  For insertion, I'd probably expect a "insert X at this location, and shift everything right".  For symmetry, I would expect that deletion should by default return a shorter object.  

In the context of an aligned sequence, removing a character may not be what you'd want to do.  A reasonable alternative would be a substitution with a gap character.  We have no way of knowing if a SeqLike is aligned relative to a reference sequence or set of sequences. 
 Perhaps if we could initialize a Deletion object with an explicit gap character, and make it  basically be substitution.

## How do mutations relate to prior work with string distance and alignment
I think the semantics @ericmjl used above would work only work if the objects are the same length.  But if you broaden it to include deletion and insertions in the general sense, we stray into pair-wise alignment algorithm territory.  It feels like we should only support it for equal length sequences for now, and it could be implemented cleanly at the SequenceLike level.

## minor/misc

* the alignment position example @ndousis posted is super confusing to me.  it seems like there are many different "positions" involved.
* I strongly disfavor the semantics of "to_index()" meaning "to zero based indexing", since that has a very specific for this library.

**Comment by ndousis** [comment]
After having reviewed the latest version in PR #63, I agree that the 1-index integer convention and `<index><mutation>` notation are the best choices for Mutation and MutationSet-- they're simple, logical, and self-consistent.

Perhaps in another issue/PR, we can explore auxiliary functions to map mutations between the convention here and
1. the seqnums defined in a PDB file
2. the `<wt><seqnum><mutation>` notation
3. alignment indices

**Comment by andrewgiessel** [comment]
@ericmjl Can we close this?

**Comment by ericmjl** [comment]
Done.
